# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f4314999dc5e277725b5eeaf0638839c809f4da436f76417231518d0491fbf6e783cf76fe6da9c122cbfc4f49fbb02ee38603a95fb581aaf196ed8ea0777d26

test:
  secret_key_base: 778b91d42f86696e4193120eba9d1d465567551084576ad17ac36747f535a33abbf911535c1da8304c77da8020eb05b2b0e19905cb280416aab99f5017264130

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
